networks:
  ansi_net:
    name: ansi_net

services:
  control_node:
    build:
      context: .
      dockerfile: Dockerfile.control.node
    networks:
      - ansi_net
    volumes:
      - $HOME/Learning/for-ansible:/root/for-ansible
    cpus: "2"
    mem_limit: 1g
    container_name: control_node
    command: tail -F anything

  target_node:
    build:
      context: .
      dockerfile: Dockerfile.target.node
    networks:
      - ansi_net
    cpus: "2"
    mem_limit: 1g
    command: tail -F anything
    

